### ISSUE TITLE
请问这个怎么部署呢？

### ISSUE THREAD

**Issue by tomatocuke** [mebtte/animal-photosynthesis#21]
我是后端，也会web的一些东西。但是不清楚typescript和ejs，您这个怎么部署的呢？

**Comment by mebtte** [comment]
我这个是 Github Actions 自动部署到 Github Pages, 部署脚本是这个 https://github.com/mebtte/animal-photosynthesis/blob/master/.github/workflows/gh_pages.yml

改一下部署脚本就可以了

**Comment by tomatocuke** [comment]
你好，我之前没了解过 Github Actions 自动部署到 Github Pages (汗)，花了挺长时间研究。

我把代码拷贝到自己的仓库，写了文档，指明你是原作者，这样可不可以呢？[链接](https://github.com/tomatocuke/tomatocuke.github.io)

改动：
1. 可能和我对文章的改动有关，出现`scripts/utils/parse_html_resource.js:37`的resouce报错情况，我加了判断undefined。
2. 使用你的Github Actions 我始终不成功，查资料做了些修改。cname似乎不需要我去掉了。
3. 名称上的更改。master改成了main，我之前用的hugo有一些文章，为了匹配把publish_time改为date了。

疑问：
1. 配置文件里的orgin是干嘛的？
2. 你的项目名不是<username>.github.io默认分配的托管地址不就变成 `<username>.github.io/仓库名` 了吗，自定义域名是怎么指向过来的。

感谢！

**Comment by mebtte** [comment]
这个没问题, 注明来源就可以了

1. origin 是你公网的域名, 比如我的就是 mebtte.com, 主要是为了设置一些 html meta 标签优化 SEO
2. github pages 支持自定义域名, 需要把自定义域名的 dns cname 记录重定向到  github, 然后 github pages 资源根目录需要一个 CNAME 文件, 内容就是自定义域名, 可以参考一下这个文档 https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by mebtte** [comment]
@tomatocuke 你理解的没错
github 分配的地址确实是 mebtte.github.com/animal-photosynthesis
这个也是可以自定义域名的
你可以看下 Github Pages 的文档

> ps: 在阮一峰大佬最新一期那里看到了你的投稿，Cool ！
> 我自己投搞的 没想到被采纳了
