### ISSUE TITLE
Python代码高亮

### ISSUE THREAD

**Issue by CYZYZG** [mebtte/animal-photosynthesis#32]
你好，当前是不是不支持Python代码高亮，如果需要增加Python代码高亮该如何修改

**Comment by mebtte** [comment]
在 prismjs [下载页面](https://prismjs.com/download.html)勾选你需要高亮的语言, 然后下载对应的 js 和 css 文件, 替换项目中的 `src/assets/prism.js` 和 `src/assets/prism.css`

**Comment by CYZYZG** [comment]
感谢
